name: TWRP Recovery Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: TWRP Compilation Action
      uses: SebaUbuntu/Action-TWRP-Device-Tree-Compiler@main
      with:
        MANIFEST_URL: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git'
        MANIFEST_BRANCH: 'twrp-11'
        DEVICE_TREE_URL: 'https://github.com/md4657800-svg/Ravoz-Z6-Pro-Twrp-img'
        DEVICE_TREE_BRANCH: 'main'
        DEVICE_NAME: 'RAVOZ_Z6_Pro'
        MAKEFILE_NAME: 'omni_RAVOZ_Z6_Pro'
        BUILD_TARGET: 'recovery'
